### ISSUE TITLE
Support nested mutations

### ISSUE THREAD

**Issue by tnrich** [Glavin001/graphql-sequelize-crud#22]
Hey there,

I just wanted to add a feature request for nested mutations. It would be awesome to have something like what is described in this blog post. https://blog.graph.cool/improving-dx-with-nested-mutations-af7711113d6

I wonder how hard it would be to do this?

Thanks!

**Comment by Glavin001** [comment]
The Medium link has been deleted. Could you provide more info?

**Comment by Glavin001** [comment]
Can be reopened when more information and/or updated blog post is provided.
