### ISSUE TITLE
ID (primary key) cannot be used in where clause of GraphQL query

### ISSUE THREAD

**Issue by michaellee8** [Glavin001/graphql-sequelize-crud#29]
Please check out [stackoverflow](https://stackoverflow.com/questions/45996730/id-cannot-be-used-in-graphql-where-clause)
Below are just my thoughts: 
Bascially when you use a `int` column in database as PK or FK, this library will treat it as a `GraphQLID`, which is considered a string. Hence when it process the client side data from the `id`  field, which is provided as `int`, it treat it as `string` and eventually says `NaN` when attempting to convert it to a number.
Please fix!

**Comment by michaellee8** [comment]
What even worse is I observed that in these `NaN` cases, `function convertFieldsFromGlobalId`, which is for doing `NaN` conversion has never been called

**Comment by Glavin001** [comment]
I have reproduced this issue and also found what I believe to be a proper fix. Hopefully publishing an update tomorrow! Thank you for your patience.
