### ISSUE TITLE
Schema could not be fetched when running using local build

### ISSUE THREAD

**Issue by aylabyuk** [Glavin001/graphql-sequelize-crud#34]
Hi @Glavin001 I was trying to use a local copy of your repo but I am getting this error whenever I import directly from the dist/src folder.

```
Schema could not be fetched.
Please check if the endpoint 'http://localhost:4000/graphql' is a valid GraphQL Endpoint.
```

Here are the steps
1. I cloned the repo to a folder
2. run "npm run all"
3. on my personal project I use
 `import { getSchema } from '../graphql-sequelize-crud/dist/src'`
4. open localhost:4000/playground

my index.js
```
import express from 'express'
import graphqlHTTP from 'express-graphql'
import { getSchema } from '../graphql-sequelize-crud/dist/src'
// import { getSchema } from 'graphql-sequelize-crud'
import { db as sequelize} from './sql/connector'

const expressPlayground = require('graphql-playground-middleware-express').default

const app = express();

sequelize.sync({
    // force: true
}).then(() => {

    const schema = getSchema(sequelize)

    app.use('/graphql', graphqlHTTP({
        schema,
        graphiql: true
    }));

    app.get('/playground', expressPlayground({ endpoint: '/graphql' }));

    const port = 4000;

    app.listen(port, () => {
        console.log(`Listening on port ${port}`)
    })
    
})
```

when using the npm package everything works as expected. The error is shown only when using a local build.
Is there anything that I missed? Why am I getting this error? 

BTW this is a great library.. I will try to contribute soon if my issue is fixed.

**Comment by aylabyuk** [comment]
successfully got it working!
A different version of graphql is used by other packages in the node_modules directory which causes this problem. My bad' 

I solved this issue by creating another **tsconfig.json** file that will have a different **outDir**. And in my own project's index.js I import the getSchema method from that directory...

**Comment by Glavin001** [comment]
If you have any changes to this library, please feel free to submit a Pull Request! Glad it is working for you now.
