### ISSUE TITLE
Works with pg-generator?

### ISSUE THREAD

**Issue by emorling** [Glavin001/graphql-sequelize-crud#35]
Doe this work with pg-generator?

The getSchema appears to fail

**Comment by Glavin001** [comment]
~~I am not familiar with pg-generator, so I would suppose the answer is **no** 😄 .~~

**Update:** Yes, see https://github.com/Glavin001/graphql-sequelize-crud/issues/35#issuecomment-367869052

**Comment by Glavin001** [comment]
> The getSchema appears to fail

If you have a specific error, please create a new Issue with steps to reproduce. Thanks!

**Comment by emorling** [comment]
Anyone that finds this: the answer is **yes, it works**

**Comment by Glavin001** [comment]
Great to hear! Is http://www.pg-generator.com/ what you are referring to?

How did you determine **yes**? You mentioned something originally failed, what did you change to make it work? Feel free to submit a Pull Request adding additional info to the README if you think it would help other pg-generator users like yourself. Thanks!

**Comment by emorling** [comment]
Correct, I am referring to pg-generator.com

I got graphql-sequelize-crud working using the models generated by pg-generator. The yes, was determined by confirming this in graphIQL. The original fault was entirely on my side.

**Comment by Glavin001** [comment]
Excellent! Let me know if you need anything else.
