### ISSUE TITLE
Wirk around id not complete

### ISSUE THREAD

**Issue by YomaDan** [Glavin001/graphql-sequelize-crud#36]
```graphql
query Ships {
  ships (where: { id: 5 }) {
    id
    title
    country {
      title
    }
  }
}

{
  "errors": [
    {
      "message": "The \"value\" argument must not be of type number. Received type number",
      "locations": [
        {
          "line": 31,
          "column": 3
        }
      ],
      "path": [
        "ships"
      ]
    }
  ],
  "data": null
}
```

**Comment by YomaDan** [comment]
query Ships {
  ships (where: { id: "5" }) {
    id
    title
    country {
      title
    }
  }
}


{
  "errors": [
    {
      "message": "Unknown column 'NaN' in 'where clause'",
      "locations": [
        {
          "line": 31,
          "column": 3
        }
      ],
      "path": [
        "ships"
      ]
    }
  ],
  "data": null
}

**Comment by Glavin001** [comment]
It would be very helpful if you make a PR changing https://github.com/Glavin001/graphql-sequelize-crud/blob/master/test/getSchema.test.ts reproducing this issue.
