### ISSUE TITLE
Add custom schemas and mutations

### ISSUE THREAD

**Issue by max10rogerio** [Glavin001/graphql-sequelize-crud#37]
How to add schemas and resolvers that are not in sequelize models?
I have this folder structure:
 - orm
   - models <- sequelize models here
 - graphql
   - MyCustomGraph
     - resolver.js
     - schema.gql
  - app.js <-- Running with apollo server

**Comment by Glavin001** [comment]
@max10rogerio You could add custom `queries` and `mutations` as shown in https://github.com/Glavin001/graphql-sequelize-crud/blob/master/demo/index.ts#L48-L92

If this does not work for you, could you describe more of what you're trying to accomplish? Or even provide a small example repository?
